### ISSUE TITLE
How to use Transaction.Send ?

### ISSUE THREAD

**Issue by UvuvwevwevweOnyetenyevweUgwemubwemOssas** [LucidOcean/multichain#2]
Hi, now my application can connect to a node, and can get chain params.

I am trying to use Send API, but I got error, I think it might be the problem of args I am using,
here is my code:
            JsonRpcResponse<string> response = null;
            response = _Client.Transaction.Send(textBox4.Text, Convert.ToDecimal(textBox3.Text));//
            ResponseLogger<string>.Log(response);

I think there should be a argument for "asset", something like asset1, asset2, could you please tell me the right way to use it?

Thanks!

**Comment by LucidOcean** [comment]
We conform to MultiChain documentation. All the help you need is available on https://www.multichain.com/developers/json-rpc-api/ 

I believe you are looking for SendAsset or SendAssetFrom

**Comment by UvuvwevwevweOnyetenyevweUgwemubwemOssas** [comment]
I am using Lucid Ocean C# API, and trying to find a way to use client.Transaction.Send 

I already tested SendAsset from command line, it works. But I don't know how to call it by using LucidOcean API, 

Here is the code from LucidOcean C# API, 

        public JsonRpcResponse<string> Send(string address, decimal amount, string comment = null, string commentTo = null)
        {
            return _Client.Execute<string>("send", 0, address, amount, comment ?? string.Empty, commentTo ?? string.Empty);
        }

As you can see, there isn't field with the name of "asset", so I have no idea which argument should be this one...

**Comment by LucidOcean** [comment]
Use SendAsset
