### ISSUE TITLE
Stream.ListStreamsAsync() returns nothing

### ISSUE THREAD

**Issue by MartinOpde** [LucidOcean/multichain#21]
```c#
public async Task<JsonRpcResponse<List<ListStreamResponse>>> GetStreams()
{
      var streams = await MultiChainClient.Stream.ListStreamsAsync();
      return streams;
}
```

returns 
```json
{
    "result": [],
    "error": null,
    "id": 0
}
```

BUT

```c#
public async Task<JsonRpcResponse<List<object>>> GetStreams()
{
       var listTransactions = await MultiChainClient.ExecuteAsync<List<object>>("liststreams", 0);
       return listTransactions;
}
```
returns
```json
{
    "result": [
        {
            "name": "root",
            "createtxid": "265055def1a4a274e8364e9ea1ac8c51a9a8f87fb7e06a0d89ffcf809d3842dc",
            "streamref": "0-0-0",
            "open": true,
            "details": {},
            "subscribed": true,
            "synchronized": true,
            "items": 0,
            "confirmed": 0,
            "keys": 0,
            "publishers": 0
        },
        {
             "..."
        }
    ],
    "error": null,
    "id": 0
}
```
Shouldn't it return the same value?

I am working with the 2.0 preview

**Comment by LucidOcean** [comment]
Yeah, we havent checked it against 2.0. 
If you send a pull request, I will accept the fix. We are little light on this project, and could do with some additional resources :)

if not I will see what I can in a week or so.

**Comment by MartinOpde** [comment]
opened a PR #22

**Comment by SunainaDG** [comment]
Has this been resolved yet? Or that's the only work around as of now?

**Comment by SunainaDG** [comment]
I think I got the solution too, your ListStreamResponse model has a field called Publishers. If you make is a dynamic field it works fine, but you guys have it as a List<string>. Change it and we are good I think, unless this has other dependencies.

**Comment by MartinOpde** [comment]
@SunainaDG It is done in PR #22

**Comment by SunainaDG** [comment]
But I just downloaded the nugget package a few days back and it still has the same issue. The project code from github however has the change. 

How do I get it in my nugget package?

**Comment by LucidOcean** [comment]
Hi. I'll make a new package soon.
