### ISSUE TITLE
liststreamkeyitems doesn't return anything when only single item exist in the stream.

### ISSUE THREAD

**Issue by revinfotech2** [LucidOcean/multichain#28]
liststreamkeyitems doesn't return anything when only single item exist in the stream.

**Comment by MaddoScientisto** [comment]
I just had this happen to me, it seems that the issue might be that the start parameter is 1 by default so it skips the only one, by setting it to -1 while doing the request I could  get the correct data

**Comment by LucidOcean** [comment]
thanks. will make the change

**Comment by MaddoScientisto** [comment]
You'd need to find a way to set it to the negative value of count, which is what the API does by default. Maybe through an overload rather than with the optional parameter
