### ISSUE TITLE
What is this error

### ISSUE THREAD

**Issue by Delasal** [LucidOcean/multichain#3]
![error](https://user-images.githubusercontent.com/30104590/30628239-bc3a734e-9df2-11e7-880d-b5db8f2031b6.jpg)
![error](https://user-images.githubusercontent.com/30104590/30628234-b35e36b6-9df2-11e7-8ceb-001de2a0757b.jpg)

**Comment by LucidOcean** [comment]
Your response - return type is not correct. You are using a string data type  when it should be GetInfoResponse
